language: go

os:
  - linux

dist: jammy

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - beanstalkd -v
  - beanstalkd -l 127.0.0.1 -p 11300 &

go:
  - "1.26"

env:
  jobs:
    - GOARCH=amd64

script:
  - go vet ./...
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
